apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  index.html: |
    <html>
      <head><title>My Custom NGINX Page</title></head>
      <body><h1>Hello from my custom index.html!</h1></body>
    </html>