apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-one
  labels:
    app: nginx-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-one
  template:
    metadata:
      labels:
        app: nginx-one
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-one
spec:
  selector:
    app: nginx-one
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
