apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two
  labels:
    app: nginx-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
        - name: nginx-two
          image: nginx:1.27.5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-two
spec:
  selector:
    app: nginx-two
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
