# Default values for hello-nginx-helm.
replicaCount: 1

image:
  repository: nginx
  tag: "1.27.5"

service:
  port: 8080

ingress:
  # The hostname is set to "{{ .Chart.Name }}.local"
  enabled: true
